apiVersion: batch/v1
kind: Job
metadata:
  generateName: rollout-deployment-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - command:
            - zap-full-scan.py
            - -t
            - https://www.example.com
          env:
            - name: VAULT_ADDR
              value: 'https://stg-vault.example.com'
          image: 'owasp/zap2docker-stable'
          imagePullPolicy: Always
          name: rollout-deployment
      restartPolicy: Never